const $=x=>document.getElementById(x),esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const tools=[['home','Home'],['bandwidth','Bandwidth'],['storage','Storage'],['cameras','Camera Schedule'],['alarms','Alarm Schedule'],['ip','IP Addressing'],['commission','Commissioning'],['survey','Site Survey'],['nvr','NVR Configuration'],['maintenance','Maintenance']];
let page='home';
function go(p){page=p;nav();render()} function nav(){$('nav').innerHTML=tools.map(x=>`<button class="${page==x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}
function field(id,n,t='text',v=''){return t==='textarea'?`<label>${n}<textarea id="${id}" rows="3">${v}</textarea></label>`:`<label>${n}<input id="${id}" type="${t}" value="${v}"></label>`}
function card(t,b){return `<div class="card"><h2>${t}</h2>${b}</div>`}
function render(){nav();let h='';
if(page==='home')h=card('CCTV Pro Toolkit',`<p>Choose a tool. Your entries are stored locally on this phone.</p><div class="grid">${tools.slice(1).map(x=>`<button onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</div>`);
if(page==='bandwidth')h=card('Bandwidth Calculator',`${field('n','Cameras','number','1')}${field('m','Main stream Mbps','number','4')}${field('s','Sub stream Mbps','number','0.5')}${field('t','Thumbnail/extra Mbps per camera','number','0')}<button onclick="band()">Calculate</button><p id="r"></p>`);
if(page==='storage')h=card('Storage Calculator',`${field('n','Cameras','number','1')}${field('b','Average bitrate Mbps/camera','number','4')}${field('d','Retention days','number','31')}${field('u','Recording duty %','number','100')}<button onclick="stor()">Calculate</button><p id="r"></p>`);
if(page==='ip')h=card('IP Addressing',`${field('base','Network base IP','text','192.168.10.0')}${field('start','Starting host','number','10')}${field('count','Number of addresses','number','20')}<button onclick="ips()">Generate</button><div id="r"></div>`);
if(page==='survey')h=card('Site Survey',`${field('site','Site name')}${field('ref','Site reference')}${field('date','Date','date')}${field('scope','Scope / requirements','textarea')}${field('network','Network / VLAN / IP details','textarea')}${field('power','Power / PoE / feeder details','textarea')}${field('cable','Cable routes / distances','textarea')}${field('access','Access / MEWP / lifting requirements','textarea')}${field('risks','Risks / constraints','textarea')}<button onclick="saveForm('survey')">Save</button> <button class="secondary" onclick="exportForm('survey')">Export</button>`);
if(page==='nvr')h=card('NVR Configuration',`${field('make','Make / model')}${field('serial','Serial number')}${field('fw','Firmware')}${field('ip','IP / subnet / gateway')}${field('storage','Storage / RAID')}${field('record','Recording / retention','textarea')}${field('network','Switch / SFP / uplink details','textarea')}${field('users','Users / roles — do not enter passwords','textarea')}<button onclick="saveForm('nvr')">Save</button> <button class="secondary" onclick="exportForm('nvr')">Export</button>`);
if(page==='cameras')h=listPage('cameras','Camera Schedule',['Camera','Location','Make/Model','IP Address','Main FPS','Main Mbps','Sub FPS','Sub Mbps','Recording']);
if(page==='alarms')h=listPage('alarms','Alarm Schedule',['Camera','Alarm type(s)','Arming type','Schedule','Notes']);
if(page==='commission')h=checkPage('commission','Commissioning Checklist',['Image','Focus/zoom','Time/NTP','Recording','Playback','Motion/analytics','Alarm inputs','Alarm outputs','Network','Storage','Users','UPS/power','Labels','Client handover']);
if(page==='maintenance')h=checkPage('maintenance','Maintenance Checklist',['Image quality','Focus','IR/night image','PTZ','Recording/playback','Storage health','Network','Time/NTP','Alarms/analytics','UPS/power','Firmware','Labels','Client issues']);
$('app').innerHTML=h}
function band(){let x=(+n.value||0)*((+m.value||0)+(+s.value||0)+(+t.value||0));r.innerHTML=`<b>${x.toFixed(2)} Mbps</b> total<br>${(x/8).toFixed(2)} MB/s`}
function stor(){let tb=(+n.value||0)*(+b.value||0)*86400*(+d.value||0)*((+u.value||0)/100)/8/1e6;r.innerHTML=`<b>${tb.toFixed(2)} TB</b> estimated storage`}
function ips(){let a=base.value.split('.').map(Number),out=[];let q=a[0]*16777216+a[1]*65536+a[2]*256+a[3]+(+start.value||1);for(let i=0;i<+count.value;i++){let z=q+i;out.push([z>>>24,(z>>>16)&255,(z>>>8)&255,z&255].join('.'))}r.innerHTML='<table><tr><th>#</th><th>IP</th></tr>'+out.map((x,i)=>`<tr><td>${i+1}</td><td>${x}</td></tr>`).join('')+'</table>'}
function listPage(k,t,cols){let rows=JSON.parse(localStorage.getItem(k)||'[]');return card(t,`<div id="rows">${rows.map((row,i)=>`<div class="item"><b>#${i+1}</b>${cols.map((c,j)=>field(k+i+'_'+j,c,'text',esc(row[j]||''))).join('')}<button class="danger" onclick="del('${k}',${i})">Delete</button></div>`).join('')}</div><button onclick="add('${k}',${cols.length})">+ Add row</button>`)}
function add(k,n){let a=JSON.parse(localStorage.getItem(k)||'[]');a.push(Array(n).fill(''));localStorage.setItem(k,JSON.stringify(a));render()}
function del(k,i){let a=JSON.parse(localStorage.getItem(k)||'[]');a.splice(i,1);localStorage.setItem(k,JSON.stringify(a));render()}
function checkPage(k,t,items){let a=JSON.parse(localStorage.getItem(k)||'null')||items.map(x=>({x,done:false,note:''}));return card(t,a.map((v,i)=>`<div class="item"><label><input type="checkbox" ${v.done?'checked':''} onchange="chk('${k}',${i},this.checked)"> ${v.x}</label><input placeholder="Notes / result" value="${esc(v.note)}" oninput="note('${k}',${i},this.value)"></div>`).join(''))}
function chk(k,i,v){let a=JSON.parse(localStorage.getItem(k)||'[]');a[i].done=v;localStorage.setItem(k,JSON.stringify(a))}
function note(k,i,v){let a=JSON.parse(localStorage.getItem(k)||'[]');a[i].note=v;localStorage.setItem(k,JSON.stringify(a))}
function saveForm(k){let o={};document.querySelectorAll('#app input,#app textarea').forEach(x=>o[x.id]=x.value);localStorage.setItem(k,JSON.stringify(o));alert('Saved on this phone')}
function exportForm(k){let b=new Blob([localStorage.getItem(k)||'{}'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=k+'.json';a.click()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
render();