const tools=[['home','⌂','Dashboard'],['sites','▦','Sites'],['bandwidth','◈','Bandwidth'],['storage','▣','Storage'],['cameras','◉','Camera Schedule'],['alarms','!','Alarm Schedule'],['ip','⌁','IP Addressing'],['commission','✓','Commissioning'],['survey','⌂','Site Survey'],['nvr','▤','NVR Configuration'],['maintenance','⚙','Maintenance']];
let page='home',siteId=localStorage.getItem('cpt_current_site')||'';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const localKey=(k)=>'cpt_'+(siteId||'nosite')+'_'+k;
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(localKey(k)))??d}catch{return d}};
const put=(k,v)=>localStorage.setItem(localKey(k),JSON.stringify(v));
function go(p){saveVisible();page=p;render()}
function nav(){$('nav').innerHTML=tools.map(t=>`<button class="${page==t[0]?'active':''}" onclick="go('${t[0]}')">${t[1]} ${t[2]}</button>`).join('')}
function field(id,label,type='text',v='',opts=[]){if(type==='select')return `<label>${label}<select id="${id}">${opts.map(o=>`<option ${String(o)==String(v)?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;if(type==='textarea')return `<label>${label}<textarea id="${id}">${esc(v)}</textarea></label>`;return `<label>${label}<input id="${id}" type="${type}" value="${esc(v)}"></label>`}
function card(title,sub,body,hero=false){return `<div class="card ${hero?'hero':''}"><h2>${title}</h2>${sub?`<p class="sub">${sub}</p>`:''}${body}</div>`}
function render(){nav();let h='';
if(!siteId&&page!=='sites')h=card('Select a site','Create or open a site first. All project records are organised under the selected site.',`<button onclick="go('sites')">Open Site Manager</button>`,true);
else if(page==='home')h=dashboard();
else if(page==='sites')h=sitesPage();
else if(page==='bandwidth')h=bandwidth();
else if(page==='storage')h=storage();
else if(page==='cameras')h=listPage('cameras','Camera Schedule',['Camera number','Location','Camera make','Camera model','IP address','Main FPS','Main Mbps','Sub FPS','Sub Mbps','Recording type'],{make:['Hikvision','Dahua','Axis','Hanwha','Bosch','Avigilon','Other'],record:['Continuous','Motion','Event','Schedule']});
else if(page==='alarms')h=listPage('alarms','Alarm Schedule',['Camera','Alarm type','Secondary alarm type','Arming type','Schedule','Action / response'],{alarm:['Intrusion','Line crossing','Region entrance','Region exit','Motion','Alarm input','Thermal','Face detection','ANPR/LPR','Tamper','Other'],arming:['Camera','NVR','VMS','External panel'],secondary:['None','Intrusion','Line crossing','Region entrance','Region exit','Motion','Alarm input','Thermal','Face detection','ANPR/LPR','Tamper','Other']});
else if(page==='ip')h=ipPage();
else if(page==='commission')h=checkPage('commission','Commissioning Checklist',['Image quality','Focus / zoom','Time / NTP','Recording','Playback','Motion / analytics','Alarm inputs','Alarm outputs','Network','Storage','User permissions','UPS / power','Labels','Client handover']);
else if(page==='maintenance')h=checkPage('maintenance','Maintenance Checklist',['Image quality','Focus','IR / night image','PTZ operation','Recording / playback','Storage health','Network health','Time / NTP','Alarms / analytics','UPS / power','Firmware','Labels','Client issues']);
else if(page==='survey')h=formPage('survey','Site Survey',['Survey date','Client / site contact','Scope / requirements','Network / VLAN / IP information','Power / PoE / feeder information','Cable routes / containment / distances','Mounting / mast / access requirements','Access / MEWP / lifting / permits','Risks / RAMS / site constraints']);
else if(page==='nvr')h=formPage('nvr','NVR Configuration',['NVR make','NVR model','Serial number','Firmware','NVR IP address','Subnet / gateway / DNS','Storage / RAID','Recording / retention settings','Network / switch / SFP / uplink details','Users / roles — do not enter passwords']);
$('app').innerHTML=h;loadVisible()}
function dashboard(){let s=getSite();return card(`Welcome to ${esc(s.name||'your site')}`,'Your project dashboard.',`<div class="grid"><button class="tool" onclick="go('cameras')"><span>◉</span><b>Cameras</b><small>Camera schedule</small></button><button class="tool" onclick="go('alarms')"><span>!</span><b>Alarms</b><small>Alarm schedules</small></button><button class="tool" onclick="go('survey')"><span>⌂</span><b>Survey</b><small>Site information</small></button><button class="tool" onclick="go('commission')"><span>✓</span><b>Commission</b><small>Completion checklist</small></button><button class="tool" onclick="go('nvr')"><span>▤</span><b>NVR</b><small>Configuration</small></button><button class="tool" onclick="go('maintenance')"><span>⚙</span><b>Maintenance</b><small>Service record</small></button><button class="tool" onclick="go('sites')"><span>▦</span><b>Site Manager</b><small>Switch site</small></button></div>`,true)}
function sitesPage(){let sites=JSON.parse(localStorage.getItem('cpt_sites')||'[]');return card('Site Manager','Create a site once, then all schedules, photos and forms belong to it.',`${sites.map(s=>`<div class="item"><div class="itemhead"><b>${esc(s.name)}</b><button class="small" onclick="openSite('${s.id}')">Open</button></div><div class="sub">${esc(s.ref||'No reference')} • ${esc(s.client||'No client')}</div></div>`).join('')||'<p class="empty">No sites yet.</p>'}<div class="actions"><button onclick="newSite()">＋ New Site</button></div>`)}
function getSite(){return (JSON.parse(localStorage.getItem('cpt_sites')||'[]')).find(x=>x.id===siteId)||{}}
function newSite(){let n=prompt('Site name');if(!n)return;let sites=JSON.parse(localStorage.getItem('cpt_sites')||'[]'),s={id:Date.now().toString(),name:n,ref:'',client:''};sites.push(s);localStorage.setItem('cpt_sites',JSON.stringify(sites));siteId=s.id;localStorage.setItem('cpt_current_site',siteId);render()}
function openSite(id){siteId=id;localStorage.setItem('cpt_current_site',id);page='home';render()}

function bandwidth(){return card('Bandwidth Calculator','Calculate combined camera traffic.',`${field('n','Cameras','number',1)}${field('m','Main stream Mbps','number',4)}${field('s','Sub stream Mbps','number',0.5)}${field('t','Thumbnail / extra Mbps per camera','number',0)}<button onclick="let x=(+n.value)*(+m.value+ +s.value+ +t.value);r.innerHTML='<b>'+x.toFixed(2)+' Mbps</b> total';">Calculate</button><div id="r" class="result">Enter values and calculate.</div>`)}
function storage(){return card('Storage Calculator','Estimate retention storage.',`${field('n','Cameras','number',1)}${field('b','Average bitrate Mbps / camera','number',4)}${field('d','Retention days','number',31)}${field('u','Recording duty %','number',100)}${field('o','Overhead %','number',10)}<button onclick="let x=+n.value*+b.value*86400*+d.value*(+u.value/100)/8/1e6*(1+ +o.value/100);r.innerHTML='<b>'+x.toFixed(2)+' TB</b> estimated';">Calculate</button><div id="r" class="result">Enter values and calculate.</div>`)}
function ipPage(){return card('IP Addressing','Generate sequential device addresses.',`${field('base','Network base IP','text','192.168.10.0')}${field('start','Starting host','number',10)}${field('count','Number of addresses','number',20)}<button onclick="let a=base.value.split('.').map(Number),q=a[0]*16777216+a[1]*65536+a[2]*256+a[3]+ +start.value,o=[];for(let i=0;i<+count.value;i++){let z=q+i;o.push([Math.floor(z/16777216)%256,Math.floor(z/65536)%256,Math.floor(z/256)%256,z%256].join('.'))}r.innerHTML='<table><tr><th>#</th><th>IP</th></tr>'+o.map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+x+'</td></tr>').join('')+'</table>'">Generate</button><div id="r"></div>`)}
function listPage(k,title,cols,opts){let rows=get(k,[]);return card(title,'Use the drop-downs wherever a standard option applies.',`<div>${rows.map((r,i)=>row(k,cols,r,i,opts)).join('')||'<p class="empty">No entries yet. Tap Add row.</p>'}</div><div class="actions"><button onclick="addRow('${k}',${cols.length})">＋ Add row</button><button class="secondary" onclick="exportKey('${k}')">Export backup</button><span class="status">● Autosaved</span></div>`)}
function row(k,cols,r,i,opts){return `<div class="item"><div class="itemhead"><b>Entry ${i+1}</b><button class="danger small" onclick="delRow('${k}',${i})">Delete</button></div>${cols.map((c,j)=>{let key=Object.keys(opts).find(x=>c.toLowerCase().includes(x));return field(`${k}_${i}_${j}`,c,key?'select':'text',r[j]||'',key?opts[key]:[])}).join('')}</div>`}
function addRow(k,n){saveVisible();let a=get(k,[]);a.push(Array(n).fill(''));put(k,a);render()}
function delRow(k,i){saveVisible();let a=get(k,[]);a.splice(i,1);put(k,a);render()}
function saveList(k){let a=get(k,[]);a.forEach((r,i)=>r.forEach((_,j)=>{let x=$(`${k}_${i}_${j}`);if(x)r[j]=x.value}));put(k,a)}
function checkPage(k,title,items){let a=get(k,items.map(x=>({item:x,done:false,note:''})));return card(title,'Tick each item and add notes. Changes save automatically.',a.map((v,i)=>`<div class="item"><label class="check"><input id="${k}c${i}" type="checkbox" ${v.done?'checked':''}> ${v.item}</label>${field(`${k}n${i}`,'Notes / result','text',v.note)}</div>`).join('')+`<div class="actions"><button class="secondary" onclick="exportKey('${k}')">Export backup</button><span class="status">● Autosaved</span></div>`)}
function saveChecks(k){let a=get(k,[]);a.forEach((v,i)=>{let c=$(`${k}c${i}`),n=$(`${k}n${i}`);if(c)v.done=c.checked;if(n)v.note=n.value});put(k,a)}
function formPage(k,title,labels){let o=get(k,{});return card(title,'Complete the site record.','<div>'+labels.map((x,i)=>field(`${k}_${i}`,x, x.toLowerCase().includes('date')?'date':x.includes('requirements')||x.includes('information')||x.includes('details')||x.includes('settings')||x.includes('scope')||x.includes('risks')?'textarea':'text',o[i]||'')).join('')+'</div><div class="actions"><button onclick="saveForm(\\''+k+'\\');alert(\\'Saved\\')">Save</button><button class="secondary" onclick="exportKey(\\''+k+'\\')">Export backup</button><span class="status">● Autosaved</span></div>')}
function saveForm(k){let o={};document.querySelectorAll(`[id^="${k}_"]`).forEach(x=>o[x.id.substring(k.length+1)]=x.value);put(k,o)}
function saveVisible(){if(page==='cameras'||page==='alarms')saveList(page);if(page==='commission'||page==='maintenance')saveChecks(page);if(page==='survey'||page==='nvr')saveForm(page)}
function loadVisible(){}
function exportKey(k){saveVisible();let b=new Blob([JSON.stringify(get(k,{}),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${getSite().name||'site'}-${k}.json`;a.click()}
document.addEventListener('input',e=>{if(e.target.id.startsWith('cameras_'))saveList('cameras');if(e.target.id.startsWith('alarms_'))saveList('alarms');if(e.target.id.startsWith('commission'))saveChecks('commission');if(e.target.id.startsWith('maintenance'))saveChecks('maintenance');if(e.target.id.startsWith('survey_'))saveForm('survey');if(e.target.id.startsWith('nvr_'))saveForm('nvr')});
document.addEventListener('change',e=>{if(e.target.id.startsWith('commission'))saveChecks('commission');if(e.target.id.startsWith('maintenance'))saveChecks('maintenance');});
window.addEventListener('beforeunload',saveVisible);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
render();